
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.72.0 (5af755147dfef8c4a2d1a8344b534e13)",
    buildSeed: 1636115650667,
    "wdosbox.wasm": {
        "size": 1480874,
        "gzSize": 495427
    },
    "wdosbox.js": {
        "size": 127696,
        "gzSize": 32858
    },
    "wlibzip.wasm": {
        "size": 114336,
        "gzSize": 53536
    },
    "wlibzip.js": {
        "size": 100444,
        "gzSize": 25896
    }
,
};
